# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-14 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bootest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bpub_date',
            field=models.DateTimeField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='btitle',
            field=models.CharField(max_length=20, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootest.BookInfo', verbose_name='来自于书籍'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hcontent',
            field=models.CharField(max_length=1000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hname',
            field=models.CharField(max_length=10, verbose_name='名字'),
        ),
    ]
