# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-22 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroinfo',
            name='hbook',
        ),
        migrations.DeleteModel(
            name='BookInfo',
        ),
        migrations.DeleteModel(
            name='HeroInfo',
        ),
    ]
