# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-14 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootest', '0002_auto_20180514_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroinfo',
            name='hcontent',
        ),
        migrations.RemoveField(
            model_name='heroinfo',
            name='hgender',
        ),
    ]
