# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-14 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootest', '0003_auto_20180514_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroinfo',
            name='hcontent',
            field=models.CharField(default='', max_length=1000, verbose_name='内容'),
        ),
    ]
