# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-14 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootest', '0004_heroinfo_hcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroinfo',
            options={'ordering': ['id']},
        ),
    ]
