# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-17 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='person_pic',
            field=models.ImageField(default='无', upload_to='person/', verbose_name='个人照片'),
        ),
    ]
